### ISSUE TITLE
project goals: PEP 0554 sub interpreters

### ISSUE THREAD

**Issue by pmp-p** [pyhandle/pyhandle#3]
Hi, i don't see anything about sub-interpreters in the readme, i know there's no C api for it (yet) and it's still a draft https://www.python.org/dev/peps/pep-0554/

But how would it integrate with the project, and is it planned to integrate anything equivalent from the start ?
I can think of :
 - switching context.
 - control and access right of current and other interpreters ( case of a supervisor ).
 - getting usefull info at runtime e.g.: is my C module already used in another sub interpreter already ?

**Comment by antocuni** [comment]
Good catch. Improving support for sub-interpreters is not one of the first goals, but designing an API which makes it easier to do it in the future definitely is: that's one of the possible usages of the `ctx` context argument, which will be passed to all the API calls. I hope 1be000f clarifies that
