### ISSUE TITLE
Concrete example

### ISSUE THREAD

**Issue by windelbouwman** [pyhandle/pyhandle#7]
What would be a good function / series of functions for a prototype?

I get the idea of this project, but nothing is more convincing than an actual example of how this would look like.

Suggestion of an example:

```c

// My cool C code

#include <HPy.h>

HPy* MyCoolFunction(HPy* obj1, HPy* obj2) {
   double a = HPy_get_float(obj1);
   // TODO: delete this object? Who is the owner of this pointer?
   double b = HPy_get_float(obj2);
   // TODO: error handling of float retrieval??
   HPy* res = Hpy_new_integer(2 + a + b);
   return res;
}

```

**Comment by mattip** [comment]
see the [api.md](https://github.com/pyhandle/pyhandle/blob/master/api.md) document for some examples.

A more complicated example might be to instantiate an entire c-extension module like rewriting the documentation page for [extending python intro](https://docs.python.org/3/extending/extending.html) in terms of the new HPy api

**Comment by antocuni** [comment]
As a very rough first approximation, the new API will be similar to this :)
```python
new_api = old.api.replace('PyObject*', 'HPy')
new_api = re.sub('^Py', 'HPy', new_api)
```

Of  course it can't always be a mechanical transliteration, but the details are yet to be discussed: this is the whole point of the project, the design is more important than the implementation, so we need to get it right. As such, we can't have concrete examples now.

Closing the issue for new, feel free to reopen if you have any doubts
